### ISSUE TITLE
Getting an error on install

### ISSUE THREAD

**Issue by joaonice** [skywinder/github-changelog-generator#329]
Since last version we are receiving an error on installation:

```sh
LoadError: cannot load such file -- bundler/gem_tasks
```

**Comment by skywinder** [comment]
got it. thanks for mention. Will try to figure out, where is a problem..

**Comment by skywinder** [comment]
Fixed

**Comment by skywinder** [comment]
src

**Comment by nunorafaelrocha** [comment]
![](https://media.giphy.com/media/yoJC2ybvWveeDpddVS/giphy.gif)

**Comment by skywinder** [comment]
@dlanileonardo seems it related with latest changes in `Rakefile`.. any ideas how to fix it?

**Comment by olleolleolle** [comment]
Is this commit a related

https://github.com/YorickPeterse/oga/commit/076d82507a491ecc0e29dd6ebce2fd0d28d2748d

**Comment by skywinder** [comment]
Seems problem in one broken test during installation. (Can't figure out, why it failed during installation and doesn't in local tests:

```
Failures:

  1) GitHubChangelogGenerator::Fetcher#github_fetch_tags when wrong token provided should raise Unauthorized error
     Failure/Error: options[:token] = INVALID_TOKEN

     RuntimeError:
       can't modify frozen Hash
     # ./spec/unit/fetcher_spec.rb:9:in `options_with_invalid_token'
     # ./spec/unit/fetcher_spec.rb:51:in `block (4 levels) in <top (required)>'
```
